services:
  react-app:
    container_name: cms
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - cms-api
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: libs/cms-ui-library
        - action: rebuild
          path: apps/cms
      
  cms-api:
    container_name: cms-api
    build:
      context: .
      dockerfile: apps/cms-api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - app-network
    develop:
      watch:
          - action: rebuild
            path: libs/cms-api-library
          - action: rebuild
            path: apps/cms-api

  cms-db:
    container_name: cms-db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  cms-keyclock:
    container_name: cms-keyclock
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev
    depends_on:
      - cms-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

volumes:
  node_modules:
  postgres_data:

networks:
  app-network:
    driver: bridge
