services:
  react-app:
    container_name: cms
    build:
      context: .
      dockerfile: apps/cms/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - cms-api
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: libs/cms-ui-library
        - action: rebuild
          path: apps/cms
      
  cms-api:
    container_name: cms-api
    build:
      context: .
      dockerfile: apps/cms-api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.docker
    networks:
      - app-network
    depends_on:
      - cms-db
    develop:
      watch:
        - action: rebuild
          path: libs/cms-api-library
        - action: rebuild
          path: apps/cms-api

  cms-db:
    container_name: cms-db
    image: postgres
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - ./prisma/keycloak:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  cms-keycloak:
    container_name: cms-keycloak
    build:
      context: .
      dockerfile: apps/cms-keycloak/Dockerfile
    depends_on:
      - cms-db
    ports:
      - "8080:8080"
    env_file:
      - .env.docker
    networks:
      - app-network
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  node_modules:
  postgres_data:
  keycloak_data:

networks:
  app-network:
    driver: bridge