name: CI

env:
  node-version: 18.x

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - prod
      - master
  workflow_dispatch:

jobs:
  Test-And-Build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Installing Dependencies
        run: npm install

      - name: Installing nx
        run: npm add nx --global

      - name: Installing vitest
        run: npm add vitest --global

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Running nx run-many lint
        run: npx nx run-many --target=lint --parallel=3

      - name: Running nx api test
        run: npx nx run-many --target=test --all=true --verbose=true --coverage=true --coverageReporters=lcov && node tools/scripts/merge.js

      - name: Running nx run-many build
        run: npx nx run-many --target=build --parallel=3

      - name: Upload build + prisma + prisma client
        uses: actions/upload-artifact@v4
        with:
          name: deploy-files
          path: |
            dist/apps/cms-api/
            prisma/
            node_modules/@prisma/client/

      - name: Running nx run-many e2e
        run: npx nx run-many --target=e2e

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  Deploy:
    needs: Test-And-Build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v2

      - name: Download deploy files
        uses: actions/download-artifact@v4
        with:
          name: deploy-files
          path: deploy/

      - name: Upload CMS API
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: deploy/dist/apps/cms-api/
          server-dir: ./domains/api.case-management-system.co.za/public_html/
          protocol: ftp

      - name: Upload Prisma folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: deploy/prisma/
          server-dir: ./domains/api.case-management-system.co.za/public_html/prisma/
          protocol: ftp

      - name: Upload Prisma Client
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: deploy/node_modules/@prisma/client/
          server-dir: ./nodevenv/domains/api.case-management-system.co.za/public_html/18/lib/node_modules/@prisma/client/
          protocol: ftp
